// An endonym is a country's name in its native language(s)
export const ENDONYMS = {
    Afghanistan: ["د افغانستان اسلامي امارت"],
    Albania: ["Republika e Shqipërisë"],
    Algeria: ["الجمهورية الجزائرية الديمقراطية الشعبية"],
    "American Samoa": ["Amerika Sāmoa"],
    Andorra: ["Principat d'Andorra"],
    Angola: ["República de Angola"],
    Anguilla: [],
    "Antigua and Barbuda": [],
    Argentina: ["República Argentina"],
    Armenia: ["Հայաստանի Հանրապետություն"],
    Aruba: [],
    Australia: [],
    Austria: ["Republik Österreich"],
    Åland: ["Ahvenanmaa"],
    Azerbaijan: ["Azərbaycan Respublikası"],
    "The Bahamas": ["The Bahamas"],
    Bahrain: ["مَمْلَكَةُ الْبَحْرَيْن"],
    Bangladesh: ["গণপ্রজাতন্ত্রী বাংলাদেশ"],
    Barbados: [],
    Belarus: ["Рэспубліка Беларусь"],
    Belgium: ["Koninkrijk België"],
    Belize: ["Bileez"],
    Benin: ["République du Bénin"],
    Bermuda: [],
    Bhutan: ["འབྲུག་རྒྱལ་ཁབ"],
    Bolivia: ["Estado Plurinacional de Bolivia"],
    Bonaire: ["Boneiru"],
    "Bosnia and Herzegovina": ["Bosna i Hercegovina"],
    Botswana: ["Lefatshe la Botswana"],
    Brazil: ["República Federativa do Brasil"],
    "British Virgin Islands": ["British Virgin Islands"],
    Brunei: ["Negara Brunei Darussalam"],
    Bulgaria: ["Република България"],
    "Burkina Faso": ["Burkĩna Faso"],
    Burundi: ["Repuburika y’Uburundi"],
    Cambodia: ["ព្រះរាជាណាចក្រកម្ពុជា"],
    Cameroon: ["République du Cameroun"],
    Canada: [],
    "Cape Verde": ["República de Cabo Verde"],
    "Cayman Islands": [],
    "Central African Republic": ["Ködörösêse tî Bêafrîka"],
    Chad: ["جمهورية تشاد"],
    Chile: ["República de Chile"],
    China: ["中华人民共和国"],
    "Christmas Island and Cocos Islands": [
        "Wilayah Pulau Krismas & Wilayah Kepulauan Cocos",
    ],
    Colombia: ["República de Colombia"],
    Comoros: ["Udzima wa Komori"],
    "Republic of the Congo": ["République du Congo"],
    "Democratic Republic of the Congo": ["République démocratique du Congo"],
    "Cook Islands": ["Kūki 'Airani"],
    "Costa Rica": ["República de Costa Rica"],
    "Côte d'Ivoire": ["Kɔdiwari Jamana"],
    Croatia: ["Republika Hrvatska"],
    Cuba: ["República de Cuba"],
    Curaçao: ["Kòrsou"],
    Cyprus: ["Κυπριακή Δημοκρατία"],
    "Czech Republic": ["Česká republika"],
    Denmark: ["Danmark"],
    Djibouti: ["جمهورية جيبوتي"],
    Dominica: ["Waitukubuli"],
    "Dominican Republic": ["República Dominicana"],
    "Timor-Leste": ["República Democrática de Timor-Leste"],
    Ecuador: ["República del Ecuador"],
    Egypt: ["جمهورية مصر العربية"],
    "El Salvador": ["República de El Salvador"],
    "Equatorial Guinea": ["República de Guinea Ecuatorial"],
    Eritrea: ["ሃገረ ኤርትራ"],
    Estonia: ["Eesti"],
    Ethiopia: ["የኢትዮጵያ ፌዴራላዊ ዴሞክራሲያዊ ሪፐብሊክ"],
    "Falkland Islands": [],
    "Faroe Islands": ["Føroyar"],
    Fiji: ["Matanitu Tugalala o Viti"],
    Finland: ["Suomen tasavalta"],
    France: [],
    "French Polynesia": ["Polynésie française"],
    Gabon: ["République gabonaise"],
    "The Gambia": [],
    Georgia: ["საქართველო"],
    Germany: ["Deutschland"],
    Ghana: [],
    Gibraltar: [],
    Greece: ["Ελληνική Δημοκρατία"],
    Greenland: ["Kalaallit Nunaat"],
    Grenada: ["Gwenad"],
    Guadeloupe: ["Gwadloup"],
    Guam: [],
    Guatemala: ["República de Guatemala"],
    Guernsey: ["Guernési"],
    Guinea: ["République de Guinée"],
    "Guinea-Bissau": ["República da Guiné-Bissau"],
    Guyana: [],
    Haiti: ["République d'Haïti"],
    Honduras: ["República de Honduras"],
    "Hong Kong": ["香港"],
    Hungary: ["Magyarország"],
    Iceland: ["Ísland"],
    India: ["Bhārat Gaṇarājya"],
    Indonesia: ["Republik Indonesia"],
    Iran: ["جمهوری اسلامی ایران"],
    Iraq: ["جُمْهُورِيَّة ٱلْعِرَاق"],
    Ireland: ["Éire"],
    "Isle of Man": ["Mannin, Ellan Vannin"],
    Israel: ["מְדִינַת יִשְׂרָאֵל"],
    Italy: ["Repubblica Italiana"],
    Jamaica: ["Jumieka"],
    Japan: ["日本国"],
    Jersey: ["Jèrri"],
    Jordan: ["المملكة الأردنية الهاشمية"],
    Kazakhstan: ["Қазақстан Республикасы"],
    Kenya: ["Jamhuri ya Kenya"],
    Kiribati: ["Ribaberiki Kiribati"],
    "North Korea": ["조선민주주의인민공화국"],
    "South Korea": ["대한민국"],
    Kosovo: ["Republika e Kosovës"],
    Kuwait: ["دَوْلَةُ ٱلْكُوَيْت"],
    Kyrgyzstan: ["Кыргыз Республикасы"],
    Laos: ["ສາທາລະນະລັດ ປະຊາທິປະໄຕ ປະຊາຊົນລາວ"],
    Latvia: ["Latvijas Republika"],
    Lebanon: ["الجمهورية اللبنانية"],
    Lesotho: ["Naha ea Lesotho"],
    Liberia: [],
    Libya: ["دولة ليبيا"],
    Liechtenstein: ["Fürstentum Liechtenstein"],
    Lithuania: ["Lietuvos Respublika"],
    Luxembourg: ["Groussherzogtum Lëtzebuerg"],
    Macau: ["澳門"],
    Madagascar: ["Repoblikan'i Madagasikara"],
    Malawi: ["Dziko la Malaŵi"],
    Malaysia: [],
    Maldives: ["ދިވެހިރާއްޖޭގެ ޖުމްހޫރިއްޔާ"],
    Mali: [],
    Malta: ["Repubblika ta' Malta"],
    "Marshall Islands": ["Aolepān Aorōkin Ṃajeḷ"],
    Martinique: ["Matinik"],
    Mauritania: ["الجمهورية الإسلامية الموريتانية"],
    Mauritius: ["République de Maurice"],
    Mayotte: [],
    Mexico: ["Estados Unidos Mexicanos"],
    "Federated States of Micronesia": [],
    Moldova: ["Republica Moldova"],
    Monaco: ["Principauté de Monaco"],
    Mongolia: ["ᠮᠤᠩᠭᠤᠯ ᠤᠯᠤᠰ"],
    Montenegro: ["Црна Гора"],
    Montserrat: [],
    Morocco: ["المملكة المغربية"],
    Mozambique: ["República de Moçambique"],
    Myanmar: ["ပြည်ထောင်စု သမ္မတ မြန်မာနိုင်ငံ"],
    Namibia: [],
    Nauru: ["Repubrikin Naoero"],
    Nepal: ["सङ्घीय लोकतान्त्रिक गणतन्त्र नेपाल"],
    Netherlands: ["Nederland", "Nederlân"],
    "New Caledonia": ["Nouvelle-Calédonie"],
    "New Zealand": ["Aotearoa"],
    Nicaragua: ["República de Nicaragua"],
    Niger: ["République du Niger"],
    Nigeria: ["Jamhuriyar Tarayyar Najeriya"],
    Niue: ["Niuē"],
    "Norfolk Island": [],
    "North Macedonia": ["Република Северна Македонија"],
    "Northern Mariana Islands": [],
    Norway: ["Kongeriket Norge"],
    Oman: ["سلطنة عُمان"],
    Pakistan: ["اسلامی جمہوریہ پاكستان"],
    Palau: ["Beluu er a Belau"],
    Palestine: ["دولة فلسطين"],
    Panama: ["República de Panamá"],
    "Papua New Guinea": ["Independen Stet bilong Papua Niugini"],
    Paraguay: ["República del Paraguay"],
    Peru: ["República del Perú"],
    Philippines: ["Republika ng Pilipinas"],
    "Pitcairn Islands": ["Pitkern Ailen"],
    Poland: ["Rzeczpospolita Polska"],
    Portugal: ["República Portuguesa"],
    "Puerto Rico": [],
    Qatar: ["دولة قطر"],
    Réunion: ["La Réunion"],
    Romania: ["România"],
    Russia: ["Российская Федерация"],
    Rwanda: ["Repubulika y'u Rwanda"],
    Saba: [],
    "Sahrawi Arab Democratic Republic": [
        "الجمهورية العربية الصحراوية الديمقراطية",
    ],
    "Saint Barthélemy": ["Saint-Barthélemy"],
    "Saint Kitts and Nevis": [],
    "Saint Martin": ["Saint-Martin"],
    "Saint Lucia": ["Sent Lisi"],
    "Saint Pierre and Miquelon": [],
    "Saint Vincent and the Grenadines": [],
    Samoa: ["Malo Saʻoloto Tutoʻatasi o Sāmoa"],
    "San Marino": ["Repubblica di San Marino"],
    "São Tomé and Príncipe": ["República Democrática de São Tomé e Príncipe"],
    "Saudi Arabia": ["المملكة العربية السعودية"],
    Senegal: ["République du Sénégal"],
    Serbia: ["Република Србија"],
    Seychelles: ["République des Seychelles"],
    "Sierra Leone": ["Ripɔblik fɔ Siera Liɔn"],
    Singapore: ["Republik Singapura"],
    "Sint Maarten": [],
    Slovakia: ["Slovenská republika"],
    Slovenia: ["Republika Slovenija"],
    "Solomon Islands": ["Solomon Aelan"],
    Somalia: ["Jamhuuriyadda Federaalka Soomaaliya"],
    "South Africa": ["iRiphabhuliki yaseNingizimu Afrika"],
    "South Sudan": [],
    Spain: ["Reino de España"],
    "Sri Lanka": ["ශ්‍රී ලංකා ප්‍රජාතාන්ත්‍රික සමාජවාදී ජනරජය"],
    "Sint Eustatius": [],
    Sudan: ["جمهورية السودان"],
    Suriname: ["Republiek Suriname"],
    Svalbard: [],
    Sweden: ["Konungariket Sverige"],
    Switzerland: ["Schweizerische Eidgenossenschaft"],
    Syria: ["اَلْجُمْهُورِيَّةُ ٱلْعَرَبِيَّةُ ٱلْسُوْرِيَّة"],
    Taiwan: ["中華民國"],
    Tajikistan: ["Ҷумҳурии Тоҷикистон"],
    Tanzania: ["Jamhuri ya Muungano wa Tanzania"],
    Thailand: ["ราชอาณาจักรไทย"],
    Togo: ["République togolaise"],
    Tokelau: [],
    Tonga: ["Puleʻanga Fakatuʻi ʻo Tonga"],
    "Trinidad and Tobago": [],
    Tunisia: ["الجمهورية التونسية"],
    Turkey: ["Türkiye Cumhuriyeti"],
    Turkmenistan: ["Türkmenistan"],
    "Turks and Caicos Islands": [],
    Tuvalu: [],
    Uganda: ["Jamhuri ya Uganda"],
    Ukraine: ["Україна"],
    "United Arab Emirates": ["الإمارات العربية المتحدة"],
    "United Kingdom": [],
    "United States of America": [],
    "United States Virgin Islands": [],
    Uruguay: ["República Oriental del Uruguay"],
    Uzbekistan: ["Ўзбекистон Республикаси"],
    Vanuatu: ["Ripablik blong Vanuatu"],
    "Vatican City": ["Stato della Città del Vaticano"],
    Venezuela: ["República Bolivariana de Venezuela"],
    Vietnam: ["Cộng hòa Xã hội chủ nghĩa Việt Nam"],
    "Wallis and Futuna": ["ʻUvea mo Futuna"],
    Yemen: ["ٱلْجُمْهُورِيَّةُ ٱلْيَمَنِيَّةُ"],
    Zambia: ["Icitungu ca Zambia"],
    Zimbabwe: ["Nyika yeZimbabwe"],
    "Western Sahara": ["الصحراء الغربية"],
    Eswatini: ["Umbuso weSwatini"],
    Antarctica: [],
    "Saint Helena": [],
};
