// An endonym is a country's name in its native language(s)
export const ENDONYMS = {
    Afghanistan: ["Afġānistān", "افغانستان"],
    Albania: ["Shqipëria"],
    Algeria: ["Dzayer", "ⴷⵣⴰⵢⴻⵔ", "Al-Jazā'ir", "الجزائر"],
    "American Samoa": ["Amerika Sāmoa", "American Samoa"],
    Andorra: ["Andorra"],
    Angola: ["Angola", "Ngola"],
    Anguilla: ["Anguilla"],
    "Antigua and Barbuda": ["Aanteega an' Baabyuuda", "Antigua and Barbuda"],
    Argentina: ["Argentina"],
    Armenia: ["Hayastán", "Հայաստան"],
    Aruba: ["Aruba"],
    Australia: ["Australia"],
    Austria: ["Österreich"],
    Åland: ["Åland", "Ahvenanmaa"],
    Azerbaijan: ["Azərbaycan"],
    "The Bahamas": ["The Bahamas"],
    Bahrain: ["Al-Baḥrayn", "البحرين"],
    Bangladesh: ["Bānglādesh", "বাংলাদেশ"],
    Barbados: ["Barbados"],
    Belarus: ["Bielaruś", "Беларусь", "Belarus", "Беларусь"],
    Belgium: ["België", "Belgique", "Belgien"],
    Belize: ["Belize"],
    Benin: ["Bénin"],
    Bermuda: ["Bermuda"],
    Bhutan: ["Druk Yul", "འབྲུག་ཡུལ"],
    Bolivia: ["Bolivia", "Buliwya", "Wuliwya", "Volívia"],
    Bonaire: ["Bonaire"],
    "Bosnia and Herzegovina": ["Bosna i Hercegovina", "Босна и Херцеговина"],
    Botswana: ["Botswana"],
    Brazil: ["Brasil"],
    "British Virgin Islands": ["British Virgin Islands"],
    Brunei: ["Brunei", "بروني"],
    Bulgaria: ["Bălgariya or Bălgarija", "България"],
    "Burkina Faso": ["Burkina Faso"],
    Burundi: ["Uburundi", "Burundi"],
    Cambodia: ["Kămpŭchéa", "កម្ពុជា"],
    Cameroon: ["Cameroun", "Cameroon"],
    Canada: ["Canada"],
    "Cape Verde": ["Cabo Verde"],
    "Cayman Islands": ["Cayman Islands"],
    "Central African Republic": ["Centrafrique", "Bêafrîka"],
    Chad: ["Tchad", "Tšād", "تشاد"],
    Chile: ["Chile"],
    China: ["Zhōngguó (Zhōnghuá Rénmín Gònghéguó)", "中国 (中华人民共和国)"],
    "Christmas Island": ["Christmas Island"],
    "Cocos Islands": ["Cocos Islands"],
    Colombia: ["Colombia"],
    Comoros: ["Komori", "Juzur al-Qumur", "جزر القمر", "Comores"],
    "Republic of the Congo": [
        "République du Congo",
        "Repubilika ya Kôngo",
        "Republíki ya Kongó",
    ],
    "Democratic Republic of the Congo": [
        "République démocratique du Congo",
        "Republíki ya Kongó Demokratíki",
        "Repubilika ya Kôngo ya Dimokalasi",
        "Jamhuri ya Kidemokrasia ya Kongo",
    ],
    "Cook Islands": ["Cook Islands", "Kūki 'Āirani"],
    "Costa Rica": ["Costa Rica"],
    "Côte d'Ivoire": ["Côte d'Ivoire"],
    Croatia: ["Hrvatska"],
    Cuba: ["Cuba"],
    Curaçao: ["Curaçao", "Kòrsou", "Curaçao"],
    Cyprus: ["Kypros", "Κύπρος", "Kıbrıs"],
    "Czech Republic": ["Česká republika", "Česko"],
    Denmark: ["Danmark"],
    Djibouti: ["Jībūtī", "جيبوتي", "Djibouti", "Jabuuti", "Gabuuti"],
    Dominica: ["Dominica"],
    "Dominican Republic": ["República Dominicana"],
    "East Timor": ["Timor Lorosa'e", "Timor-Leste"],
    Ecuador: ["Ecuador"],
    Egypt: ["Misr or Masr", "مصر"],
    "El Salvador": ["El Salvador"],
    "Equatorial Guinea": [
        "Guinea Ecuatorial",
        "Guinée équatoriale",
        "Guiné Equatorial",
    ],
    Eritrea: ["Iritriya", "إرتريا", "Ertra", "ኤርትራ"],
    Estonia: ["Eesti"],
    "Eswatini\n(formerly Swaziland)": ["Eswatini", "eSwatini"],
    Ethiopia: ["Ityop'ia", "ኢትዮጵያ"],
    "Falkland Islands": ["Falkland Islands"],
    "Faroe Islands": ["Føroyar", "Færøerne"],
    Fiji: ["Fiji", "Viti", "फ़िजी"],
    Finland: ["Suomi", "Finland"],
    France: ["France"],
    "French Guiana": ["Guyane"],
    "French Polynesia": ["Polynésie française", "Pōrīnetia Farāni"],
    Gabon: ["Gabon"],
    "The Gambia": [
        "The Gambia",
        "Kambiya",
        "ߞߊߡߓߌߦߊ",
        "Gambi",
        "𞤘𞤢𞤥𞤦𞤭",
        "Gámbi",
    ],
    Georgia: ["Sak'art'velo", "საქართველო"],
    Germany: ["Deutschland"],
    Ghana: ["Ghana", "Gaana", "Gana", "Gana"],
    Gibraltar: ["Gibraltar"],
    Greece: ["Ellada", "Ελλάδα or Hellas", "Ελλάς"],
    Greenland: ["Kalaallit Nunaat", "Grønland"],
    Grenada: ["Grenada"],
    Guadeloupe: ["Guadeloupe"],
    Guam: ["Guam", "Guåhån"],
    Guatemala: ["Guatemala"],
    Guernsey: ["Guernsey", "Guernési"],
    Guinea: ["Guinée", "Gine", "ߖߌ߬ߣߍ߫", "Gine", "𞤘𞤭𞤲𞤫"],
    "Guinea-Bissau": [
        "Guiné-Bissau",
        "Gine-Bisaawo",
        "𞤘𞤭𞤲𞤫 𞤄𞤭𞤧𞤢𞥄𞤱𞤮",
        "Gine-Bisawo",
        "ߖߌ߬ߣߍ߫ ߓߌߛߊߥߏ߫",
    ],
    Guyana: ["Guyana"],
    Haiti: ["Haïti", "Ayiti"],
    Honduras: ["Honduras"],
    "Hong Kong": ["Hong Kong", "Heung Gong", "香港"],
    Hungary: ["Magyarország"],
    Iceland: ["Ísland"],
    India: [
        "Bhārôt",
        "ভাৰত",
        "Bhārôt",
        "ভারত",
        "India",
        "Bhārat",
        "ભારત",
        "Bhārat",
        "भारत",
        "Bhārata",
        "ಭಾರತ",
        "Bhārat",
        "भारत",
        "Bhāratam",
        "ഭാരതം",
        "Bhārat",
        "भारत",
        "Bhārat",
        "भारत",
        "Bhārata",
        "ଭାରତ",
        "Bhārat",
        "ਭਾਰਤ",
        "Bhāratam",
        "भारतम्",
        "Bāratam",
        "பாரதம்",
        "Bhāratadēśam",
        "భారతదేశం",
    ],
    Indonesia: ["Indonesia"],
    Iran: ["Īrān", "ایران"],
    Iraq: ["Al-'Iraq", "العراق", "Êraq", "عێراق"],
    Ireland: ["Éire", "Ireland"],
    "Isle of Man": ["Isle of Man or Mann", "Ellan Vannin or Mannin"],
    Israel: ["Yisra'el", "ישראל", "Israʼiyl", "إسرائيل"],
    Italy: ["Italia"],
    Jamaica: ["Jamaica"],
    Japan: ["Nihon", "Nippon", "日本"],
    Jersey: ["Jersey", "Jersey", "Jèrri"],
    Jordan: ["Al-’Urdun", "الأردن"],
    Kazakhstan: ["Qazaqstan", "Қазақстан", "Kazakhstán", "Казахстан"],
    Kenya: ["Kenya"],
    Kiribati: ["Kiribati"],
    "North Korea": ["Chosŏn", "조선 / 朝鮮", "Bukchosŏn", "북조선"],
    "South Korea": ["Hanguk", "한국 / 韓國", "Namhan", "남한"],
    Kosovo: ["Kosova", "Kosovo", "Косово"],
    Kuwait: ["Dawlat ul-Kuwayt", "دولة الكويت", "il-ikwet", "الكويت"],
    Kyrgyzstan: ["Kyrgyzstan", "Кыргызстан", "Kyrgyzstan", "Кыргызстан"],
    Laos: ["Lao", "ປະເທດລາວ"],
    Latvia: ["Latvija"],
    Lebanon: ["Lubnān", "لبنان", "Liban"],
    Lesotho: ["Lesotho"],
    Liberia: ["Liberia"],
    Libya: ["Libya", "Lībiyā", "ليبيا", "ⵍⵉⴱⵢⴰ"],
    Liechtenstein: ["Liechtenstein"],
    Lithuania: ["Lietuva"],
    Luxembourg: ["Lëtzebuerg", "Luxemburg", "Luxembourg"],
    Macau: ["Oumún", "澳門", "Macau"],
    Madagascar: ["Madagasikara", "Madagascar"],
    Malawi: ["Malawi", "Malaŵi"],
    Malaysia: ["Malaysia"],
    Maldives: ["Dhivehi Raajje", "ދިވެހިރާއްޖެ"],
    Mali: ["Mali", "ߡߊ߬ߟߌ", "Maali", "𞤃𞤢𞥄𞤤𞤭"],
    Malta: ["Malta", "Malta"],
    "Marshall Islands": ["Aorōkin Ṃajeḷ", "Marshall Islands"],
    Martinique: ["Martinique"],
    Mauritania: [
        "Muritan / Agawec",
        "ⵎⵓⵔⵉⵜⴰⵏ / ⴰⴳⴰⵡⵛ",
        "Mūrītānyā",
        "موريتانيا",
    ],
    Mauritius: ["Mauritius", "Maurice", "Moris"],
    Mayotte: ["Mayotte", "Maore"],
    Mexico: ["México", "Mēxihco"],
    "Federated States of Micronesia": ["Federated States of Micronesia"],
    Moldova: ["Moldova"],
    Monaco: ["Monaco", "Múnegu"],
    Mongolia: ["Mongol Uls", "Монгол Улс", "ᠮᠤᠩᠭᠤᠯ", "ᠤᠯᠤᠰ"],
    Montenegro: ["Crna Gora", "Црна Гора"],
    Montserrat: ["Montserrat"],
    Morocco: ["Amerruk / Elmeɣrib", "ⴰⵎⵔⵔⵓⴽ / ⵍⵎⵖⵔⵉⴱ", "Al-maɣréb", "المغرب"],
    Mozambique: ["Moçambique", "Muzambhiki"],
    "Myanmar (or Burma)": ["Myanma", "မြန်မာ"],
    Namibia: ["Namibia", "Namibia", "Namibië", "Namibia", "Namibia"],
    Nauru: ["Nauru", "Naoero"],
    Nepal: ["Nepāl", "नेपाल"],
    Netherlands: ["Nederland", "Nederlân"],
    "New Caledonia": ["Nouvelle-Calédonie"],
    "New Zealand": ["New Zealand", "Aotearoa"],
    Nicaragua: ["Nicaragua"],
    Niger: ["Niger", "Nijar"],
    Nigeria: ["Nigeria", "Nijeriya", "Naìjíríyà", "Nàìjíríà"],
    Niue: ["Niuē", "Niue"],
    "Norfolk Island": ["Norfolk Island", "Norf'k Ailen"],
    "North Macedonia": [
        "Severna Makedonija",
        "Северна Македонија",
        "Maqedonia e Veriut",
    ],
    "Northern Mariana Islands": ["Northern Mariana Islands", "Notte Mariånas"],
    Norway: ["Norge", "Noreg", "Norga", "Vuodna", "Nöörje"],
    Oman: ["‘Umān", "عُمان"],
    Pakistan: ["Pakistan", "Pākistān", "پاکستان"],
    Palau: ["Belau", "Palau"],
    Palestine: ["Filasṭīn", "فلسطين"],
    Panama: ["Panamá"],
    "Papua New Guinea": ["Papua New Guinea", "Papua Niugini", "Papua Niu Gini"],
    Paraguay: ["Paraguay", "Paraguái"],
    Peru: ["Perú", "Piruw"],
    Philippines: ["Pilipinas", "Philippines"],
    "Pitcairn Islands": ["Pitcairn Islands", "Pitkern Ailen"],
    Poland: ["Polska"],
    Portugal: ["Portugal"],
    "Puerto Rico": ["Puerto Rico"],
    Qatar: ["Qaṭar", "قطر"],
    Réunion: ["La Réunion"],
    Romania: ["România"],
    Russia: ["Rossiya or Rossiâ", "Россия[5]"],
    Rwanda: ["Rwanda"],
    Saba: ["Saba"],
    "Sahrawi Arab Democratic Republic": [
        "Al-Jumhūrīyah al-‘Arabīyah aṣ-Ṣaḥrāwīyah ad-Dīmuqrāṭīyah",
        "",
        "الجمهورية العربية الصحراوية الديمقراطية",
        "",
        "República Árabe Saharaui Democrática",
    ],
    "Saint Barthélemy": ["Saint-Barthélemy"],
    "Saint Helena, Ascension and Tristan da Cunha": [
        "Saint Helena, Ascension and Tristan da Cunha",
    ],
    "Saint Kitts and Nevis": ["Saint Kitts and Nevis"],
    "Saint Martin": ["Saint-Martin"],
    "Saint Lucia": ["Saint Lucia"],
    "Saint Pierre and Miquelon": ["Saint-Pierre et Miquelon"],
    "Saint Vincent and the Grenadines": ["Saint Vincent and the Grenadines"],
    Samoa: ["Samoa", "Sāmoa"],
    "San Marino": ["San Marino"],
    "São Tomé and Príncipe": ["São Tomé e Príncipe"],
    "Saudi Arabia": [
        "Al-Mamlaka Al-‘Arabiyyah as Sa‘ūdiyyah",
        "المملكة العربية السعودية",
    ],
    Senegal: ["Sénégal", "Senegaal"],
    Serbia: ["Srbija", "Србија"],
    Seychelles: ["Sesel", "Seychelles", "Seychelles"],
    "Sierra Leone": ["Sierra Leone"],
    Singapore: [
        "Singapura",
        "Singapore",
        "Xīnjiāpō",
        "新加坡",
        "Singapur",
        "சிங்கப்பூர்",
    ],
    "Sint Maarten": ["Sint Maarten", "Sint Maarten"],
    Slovakia: ["Slovensko"],
    Slovenia: ["Slovenija"],
    "Solomon Islands": ["Solomon Islands", "Solomon Aelan"],
    Somalia: ["Soomaaliya", "aş-Şūmāl", "الصومال"],
    "South Africa": [
        "South Africa",
        "Suid-Afrika",
        "iNingizimu Afrika",
        "uMzantsi Afrika",
        "Afrika-Borwa",
        "Afrika Borwa",
        "Aforika Borwa",
        "Afurika Tshipembe",
        "Afrika Dzonga",
        "iNingizimu Afrika",
        "iSewula Afrika",
    ],
    "South Sudan": ["South Sudan", "Paguot Thudän", "Sudan Kusini"],
    Spain: ["España", "Espanya", "Espainia", "Espanha"],
    "Sri Lanka": ["Sri Lankā", "ශ්‍රී ලංකාව", "இலங்கை"],
    "Sint Eustatius": ["Sint Eustatius", "Statia"],
    Sudan: ["As-Sudan", "السودان"],
    Suriname: ["Suriname"],
    Svalbard: ["Svalbard"],
    Sweden: ["Sverige"],
    Switzerland: ["Schweiz", "Suisse", "Svizzera", "Svizra"],
    Syria: ["Suriyah", "سورية"],
    "Taiwan (Republic of China)": [
        "Zhōnghuá Mínguó or Táiwān",
        "中華民國 or 臺灣/台灣",
    ],
    Tajikistan: ["Tojikiston", "Тоҷикистон"],
    Tanzania: ["Tanzania"],
    Thailand: [
        "Thai, Prathet Thai, Ratcha-anachak Thai",
        "ไทย, ประเทศไทย, ราชอาณาจักรไทย",
    ],
    Togo: ["Togo", "Togo", "Togo"],
    Tokelau: ["Tokelau"],
    Tonga: ["Tonga"],
    "Trinidad and Tobago": ["Trinidad and Tobago"],
    Tunisia: ["Tunes", "ⵜⵓⵏⵙ", "Tūns", "تونس"],
    Turkey: ["Türkiye"],
    Turkmenistan: ["Türkmenistan"],
    "Turks and Caicos Islands": ["Turks and Caicos Islands"],
    Tuvalu: ["Tuvalu"],
    Uganda: ["Uganda"],
    Ukraine: ["Ukrajina", "Україна"],
    "United Arab Emirates": [
        "Al-’Imārat Al-‘Arabiyyah Al-Muttaḥidah",
        "الإمارات العربيّة المتّحدة",
    ],
    "United Kingdom": [
        "United Kingdom or Britain",
        "Y Deyrnas Unedig",
        "Unitit Kinrick",
        "Rìoghachd Aonaichte",
        "Ríocht Aontaithe",
        "An Rywvaneth Unys",
    ],
    "United States of America": [
        "United States or America",
        "Estados Unidos",
        "États-Unis",
        "‘Amelika Hui Pū ‘ia",
    ],
    "United States Virgin Islands": ["United States Virgin Islands"],
    Uruguay: ["Uruguay"],
    Uzbekistan: ["O‘zbekiston", "Ўзбекистон"],
    Vanuatu: ["Vanuatu"],
    "Vatican City": ["Civitas Vaticana", "Città del Vaticano"],
    Venezuela: ["Venezuela"],
    Vietnam: ["Việt Nam"],
    "Wallis and Futuna": ["Wallis-et-Futuna", "ʻUvea mo Futuna"],
    Yemen: ["Al-Yaman", "اليمن"],
    Zambia: ["Zambia"],
    Zimbabwe: ["Zimbabwe"],
};
